name: Manual Echo

on: push

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Workflow triggered!"

  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: second-step
        run: echo "this is second step 22"

  third-job:
    runs-on: ubuntu-latest
    steps:
      - name: third-step
        run: echo "this is third step"
