name: Manual Echo

on: push

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Workflow triggered manually!"

  second-job:
    runs-on: ubunut-latest
    steps:
      - name: second-step
        run: echo "this is second step"
